name: NodeApp CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-1
  FRONTEND_REPOSITORY: nodeapp-frontend
  BACKEND_REPOSITORY: nodeapp-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credenatials@v6
        with:
          role-to-assume: arn:aws:iam::968585507521:role/GitHubActionsECRRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build backend image
        env:
          ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
          IMAGE_TAG: ${{github.sha}}
        run: |
          docker build -t $ECR_REGISTRY/$BACKEND_REPOSITORY:$IMAGE_TAG ./node-server-vm

      - name: Build frontend image
        env:
          ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
          IMAGE_TAG: ${{github.sha}}
        run: |
          docker build -t $ECR_REGISTRY/$FRONTEND_REPOSITORY:$IMAGE_TAG ./react-vm

      - name: Push backend image
        env:
          ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
          IMAGE_TAG: ${{github.sha}}
        run: |
          docker push $ECR_REGISTRY/$BACKEND_REPOSITORY:$IMAGE_TAG

      - name: Push frontend image
        env:
          ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
          IMAGE_TAG: ${{github.sha}}
        run: |
          docker push $ECR_REGISTRY/$FRONTEND_REPOSITORY:$IMAGE_TAG
